theme: jekyll-theme-minimal

google_analytics: G-1NMPN6CTJN

title: Steve Geinitz
description: Steve Geinitz
url: https://github.com/sgeinitz
locale: en_US
logo: /img/profile128.png
profile_gh: /img/github32.png
profile_li: /img/linkedin32.png
profile_rg: /img/researchgate32.png
profile_gs: /img/googlescholar32.png
page_css:
  - /assets/css/custom.css
