theme: jekyll-theme-minimal

google_analytics: G-1NMPN6CTJN

title: Steve Geinitz
description: Steve Geinitz
url: https://github.com/sgeinitz
locale: en_US
logo: /img/profile128.png
profile_gh: /img/github48.png
profile_rg: /img/linkedin48.png
profile_li: /img/researchgate48.png
page_css:
  - /assets/css/custom.css
